const games = {
    PlayStation: {
        Action: ["Uncharted", "God of War", "Spider-Man", "Ghost of Tsushima", "Infamous Second Son", "Ratchet & Clank", "Tomb Raider", "The Last Guardian", "Killzone", "Resistance", "Nioh", "Devil May Cry 5", "Shadow of the Colossus", "Ape Escape", "Heavenly Sword", "Sekiro: Shadows Die Twice", "Control", "Vanquish", "Bayonetta", "Horizon Forbidden West", "Returnal", "Deathloop", "Sifu", "Mad Max", "Just Cause 4", "Metal Gear Rising: Revengeance", "Ninja Gaiden Sigma", "Darksiders", "Prince of Persia", "Star Wars Jedi: Fallen Order", "Infamous Second Light", "Godfall", "LittleBigPlanet", "Granblue Fantasy Versus", "Street Fighter V", "Tekken 7", "Virtua Fighter 5", "Dead or Alive 6", "Marvel vs. Capcom: Infinite", "Samurai Shodown", "Soulcalibur VI", "BlazBlue: Cross Tag Battle", "Mortal Kombat 11", "Dragon Ball FighterZ", "Guilty Gear Strive"],
        Adventure: ["The Last of Us", "Horizon Zero Dawn", "Shadow of the Colossus", "Detroit: Become Human", "Until Dawn", "Heavy Rain", "Beyond: Two Souls", "Life is Strange", "The Wolf Among Us", "Firewatch", "What Remains of Edith Finch", "Journey", "ABZÛ", "The Witness", "Myst", "Outer Wilds", "Manifold Garden", "Oxenfree", "Inside", "Limbo", "Brothers: A Tale of Two Sons", "Kentucky Route Zero", "Twelve Minutes", "A Short Hike", "Night in the Woods", "Gris", "Rime", "Spiritfarer", "Ori and the Blind Forest", "Ori and the Will of the Wisps", "Little Nightmares", "Little Nightmares II", "Telling Lies", "Erica", "The Vanishing of Ethan Carter", "The Stanley Parable", "Return of the Obra Dinn", "Gone Home", "Dear Esther", "Disco Elysium", "Thimbleweed Park", "Broken Age", "The Long Dark", "Subnautica", "Raft", "No Man's Sky"],
        RPG: ["Final Fantasy XV", "Persona 5", "Bloodborne", "Dragon Quest XI", "Ni No Kuni II", "Elden Ring", "Demon's Souls", "Dark Souls III", "The Witcher 3: Wild Hunt", "Skyrim", "Fallout 4", "Mass Effect Legendary Edition", "Cyberpunk 2077", "Divinity: Original Sin 2", "Baldur's Gate 3", "Dragon Age: Inquisition", "Tales of Arise", "Ys VIII: Lacrimosa of Dana", "Xenoblade Chronicles", "Fire Emblem: Three Houses", "Octopath Traveler", "Bravely Default II", "Pokemon Scarlet", "Pokemon Violet", "Shin Megami Tensei V", "Monster Hunter World", "Monster Hunter Rise", "Kingdom Hearts III", "Kingdom Hearts II", "Chrono Trigger", "EarthBound", "Final Fantasy VI", "Secret of Mana", "Dragon Quest III", "Tales of Symphonia", "Star Ocean: The Last Hope", "Persona 4 Golden", "Persona 3", "Valkyria Chronicles", "The Legend of Heroes: Trails of Cold Steel", "The Legend of Heroes: Trails in the Sky", "Suikoden II", "Golden Sun", "Phantasy Star Online 2", "Rogue Galaxy", "Blue Dragon", "Lost Odyssey", "White Knight Chronicles"],
        Horror: ["Resident Evil 7", "Silent Hill 2", "The Evil Within", "Until Dawn", "Dead by Daylight", "Resident Evil Village", "Resident Evil 4", "Resident Evil 2", "Resident Evil 3", "Silent Hill", "Silent Hill 3", "Silent Hill 4", "Amnesia: The Dark Descent", "Amnesia: Rebirth", "Outlast", "Outlast 2", "SOMA", "Visage", "The Medium", "Alan Wake", "Alan Wake Remastered", "Fatal Frame", "Fatal Frame II", "Clock Tower", "Clock Tower 3", "Haunting Ground", "Rule of Rose", "Obscure", "Obscure II", "F.E.A.R.", "F.E.A.R. 2", "Condemned: Criminal Origins", "Condemned 2: Bloodshot", "The Callisto Protocol", "The Quarry", "Little Nightmares", "Little Nightmares II", "Doki Doki Literature Club!", "Inside", "Limbo", "Darkwood", "Martha is Dead", "Tormented Souls", "Song of Horror", "Madison", "Agony", "Hellblade: Senua's Sacrifice"],
        Sports: ["FIFA 23", "NBA 2K23", "Gran Turismo Sport", "MLB The Show", "Tony Hawk's Pro Skater 1+2", "Rocket League", "Madden NFL 22", "Madden NFL 23", "PES 2021", "PES 2022", "WWE 2K22", "WWE 2K23", "EA Sports UFC 4", "Fight Night Champion", "Super Mega Baseball 3", "Golf With Your Friends", "Hot Shots Golf", "Everybody's Golf", "Mario Golf: Super Rush", "Mario Tennis Aces", "NBA Live 19", "FIFA Street", "NBA Jam", "NBA Playground", "Skater XL", "Session", "Football Manager 2022", "Football Manager 2023", "NHL 22", "NHL 23", "Riders Republic", "Descenders", "Steep", "SnowRunner", "Forza Horizon 4", "Forza Horizon 5", "Forza Motorsport 7", "Gran Turismo 7", "Tour de France 2022", "Olympic Games Tokyo 2020", "Tennis World Tour 2", "AO Tennis 2", "Handball 21", "Rugby 22", "Cricket 22", "The Golf Club 2019", "The Golf Club 2022", "Dirt 5", "WRC 10", "WRC Generations"]
    },
    PS2: {
        Action: ["God of War", "Devil May Cry", "Metal Gear Solid 2", "Metal Gear Solid 3", "Grand Theft Auto: San Andreas"],
        Adventure: ["Kingdom Hearts", "Kingdom Hearts II", "Shadow of the Colossus", "ICO", "Okami"],
        RPG: ["Final Fantasy X", "Final Fantasy XII", "Dragon Quest VIII", "Persona 3", "Persona 4"],
        Horror: ["Silent Hill 2", "Silent Hill 3", "Silent Hill 4: The Room", "Fatal Frame", "Fatal Frame II: Crimson Butterfly"],
        Sports: ["FIFA 10", "Pro Evolution Soccer 6", "NBA 2K9", "Gran Turismo 4", "SSX Tricky"]
    },
    PS3: {
        Action: [
            "The Last of Us", "Uncharted: Drake's Fortune", "Uncharted 2: Among Thieves", "Uncharted 3: Drake's Deception", "God of War III", "God of War: Ascension", "Metal Gear Solid 4: Guns of the Patriots", "Batman: Arkham Asylum", "Batman: Arkham City", "Infamous", "Infamous 2", "Infamous: Festival of Blood", "Red Dead Redemption", "Grand Theft Auto IV", "Grand Theft Auto V", "Assassin's Creed", "Assassin's Creed II", "Assassin's Creed Brotherhood", "Assassin's Creed Revelations", "Assassin's Creed III", "Devil May Cry 4", "Heavenly Sword", "Darksiders", "Darksiders II", "Bayonetta", "Tomb Raider", "Max Payne 3", "Prototype", "Prototype 2", "Saints Row 2", "Saints Row: The Third", "Saints Row IV", "Far Cry 2", "Far Cry 3", "Far Cry 4", "Call of Duty: Modern Warfare", "Call of Duty: Modern Warfare 2", "Call of Duty: Modern Warfare 3", "Call of Duty: Black Ops", "Call of Duty: Black Ops II", "Killzone 2", "Killzone 3", "Resistance: Fall of Man", "Resistance 2", "Resistance 3", "Borderlands", "Borderlands 2", "Deadpool", "Watch Dogs"
        ],
        Adventure: [
            "Journey", "Heavy Rain", "Beyond: Two Souls", "The Walking Dead: Season One", "The Walking Dead: Season Two", "Tales from the Borderlands", "The Wolf Among Us", "LA Noire", "Lego Marvel Super Heroes", "Lego Batman 2: DC Super Heroes", "Lego Batman 3: Beyond Gotham", "Lego The Lord of the Rings", "Lego Star Wars: The Complete Saga", "Lego Star Wars III: The Clone Wars", "Lego Indiana Jones: The Original Adventures", "Lego Indiana Jones 2: The Adventure Continues", "The Lego Movie Videogame", "Alice: Madness Returns", "Enslaved: Odyssey to the West", "Ni no Kuni: Wrath of the White Witch", "Catherine", "Child of Light", "Brothers: A Tale of Two Sons", "Okami HD", "The Prince of Persia Trilogy", "Prince of Persia: The Forgotten Sands", "Prince of Persia", "Shadow of the Colossus HD", "Ico HD", "LittleBigPlanet", "LittleBigPlanet 2", "LittleBigPlanet Karting", "Ratchet & Clank Future: Tools of Destruction", "Ratchet & Clank Future: A Crack in Time", "Ratchet & Clank: Into the Nexus", "Sly Cooper: Thieves in Time", "Jak and Daxter Collection", "Tomb Raider Trilogy", "Puppeteer", "Dragon's Dogma", "Dragon's Dogma: Dark Arisen", "Mirror's Edge", "Gravity Rush Remastered", "Valkyria Chronicles", "The Last Guardian", "Until Dawn", "Folklore", "Afrika"
        ],
        RPG: [
            "Dark Souls", "Demon's Souls", "Dark Souls II", "Final Fantasy XIII", "Final Fantasy XIII-2", "Lightning Returns: Final Fantasy XIII", "Final Fantasy XIV", "The Elder Scrolls V: Skyrim", "Dragon Age: Origins", "Dragon Age II", "Dragon Age: Inquisition", "Fallout 3", "Fallout: New Vegas", "Mass Effect 2", "Mass Effect 3", "Persona 5", "Ni no Kuni: Wrath of the White Witch", "Tales of Xillia", "Tales of Xillia 2", "Tales of Graces f", "Tales of Symphonia Chronicles", "Kingdom Hearts HD 1.5 Remix", "Kingdom Hearts HD 2.5 Remix", "Kingdoms of Amalur: Reckoning", "South Park: The Stick of Truth", "The Witcher 2: Assassins of Kings", "Rogue Galaxy HD", "Star Ocean: The Last Hope International", "Eternal Sonata", "Disgaea 3: Absence of Justice", "Disgaea 4: A Promise Unforgotten", "Valkyria Chronicles", "Resonance of Fate", "White Knight Chronicles", "White Knight Chronicles II", "Blue Dragon", "Lost Odyssey", "Xenoblade Chronicles", "Suikoden III HD", "Suikoden IV HD", "Suikoden V HD", "Atelier Rorona: The Alchemist of Arland", "Atelier Totori: The Adventurer of Arland", "Atelier Meruru: The Apprentice of Arland", "Atelier Ayesha: The Alchemist of Dusk", "Atelier Escha & Logy: Alchemists of the Dusk Sky"
        ],
        Horror: [
            "Dead Space", "Dead Space 2", "Dead Space 3", "Resident Evil 5", "Resident Evil 6", "Resident Evil: Revelations", "Resident Evil: Revelations 2", "Silent Hill: Homecoming", "Silent Hill: Downpour", "Silent Hill HD Collection", "Amnesia: The Dark Descent", "Amnesia: A Machine for Pigs", "Outlast", "Outlast: Whistleblower", "SOMA", "Slender: The Arrival", "The Evil Within", "The Evil Within 2", "Alien: Isolation", "The Walking Dead: Survival Instinct", "The Last of Us", "Condemned 2: Bloodshot", "F.E.A.R. 3", "Until Dawn", "Alan Wake", "Alan Wake's American Nightmare", "Obscure II", "Haunting Ground HD", "Clock Tower HD", "Fatal Frame HD", "Fatal Frame II: Crimson Butterfly HD", "Fatal Frame III: The Tormented HD", "Rule of Rose HD", "Manhunt HD", "Kuon HD", "Echo Night HD", "Dino Crisis HD", "Dino Crisis 2 HD", "Resident Evil 4 HD", "Parasite Eve HD", "Parasite Eve II HD", "Project Zero HD", "Darkwood", "Friday the 13th: The Game", "Layers of Fear", "Layers of Fear 2", "Daylight", "Agony", "Blair Witch"
        ],
        Sports: [
            "FIFA 10", "FIFA 11", "FIFA 12", "FIFA 13", "FIFA 14", "FIFA 15", "FIFA 16", "Pro Evolution Soccer 2010", "Pro Evolution Soccer 2011", "Pro Evolution Soccer 2012", "Pro Evolution Soccer 2013", "Pro Evolution Soccer 2014", "NBA 2K10", "NBA 2K11", "NBA 2K12", "NBA 2K13", "NBA 2K14", "NBA 2K15", "NBA 2K16", "NBA Live 10", "NBA Live 11", "NBA Live 12", "NHL 10", "NHL 11", "NHL 12", "NHL 13", "NHL 14", "Madden NFL 10", "Madden NFL 11", "Madden NFL 12", "Madden NFL 13", "Madden NFL 14", "Tiger Woods PGA Tour 10", "Tiger Woods PGA Tour 11", "Tiger Woods PGA Tour 12", "Tiger Woods PGA Tour 13", "Tiger Woods PGA Tour 14", "SSX", "SSX Tricky", "Gran Turismo 5", "Gran Turismo 6", "MLB The Show 10", "MLB The Show 11", "MLB The Show 12", "MLB The Show 13", "MLB The Show 14", "Tony Hawk's Pro Skater HD", "Tony Hawk's Pro Skater 3 HD", "Tony Hawk's Pro Skater 4 HD"
        ]
    },
    PS4: {
        Action: [
            "The Last of Us Part II", "Uncharted 4: A Thief's End", "God of War", "Horizon Zero Dawn", "Marvel's Spider-Man", "Ghost of Tsushima", "Red Dead Redemption 2", "Sekiro: Shadows Die Twice", "Bloodborne", "Assassin's Creed Valhalla", "Assassin's Creed Odyssey", "Assassin's Creed Origins", "Shadow of the Tomb Raider", "Rise of the Tomb Raider", "Tomb Raider: Definitive Edition", "Far Cry 5", "Far Cry New Dawn", "Far Cry Primal", "Far Cry 4", "Devil May Cry 5", "Metal Gear Solid V: The Phantom Pain", "Metal Gear Solid V: Ground Zeroes", "Dying Light", "Dying Light 2", "Control", "The Evil Within", "The Evil Within 2", "Nioh", "Nioh 2", "Infamous Second Son", "Infamous First Light", "Mad Max", "Just Cause 3", "Just Cause 4", "Watch Dogs", "Watch Dogs 2", "Watch Dogs Legion", "Cyberpunk 2077", "Middle-earth: Shadow of Mordor", "Middle-earth: Shadow of War", "Batman: Arkham Knight", "Ratchet & Clank", "Lego Marvel Super Heroes", "Lego Marvel Super Heroes 2", "Lego DC Super-Villains", "Death Stranding", "Days Gone", "Immortals Fenyx Rising", "Control: Ultimate Edition", "The Order: 1886"
        ],
        Adventure: [
            "The Last Guardian", "Journey", "Heavy Rain", "Beyond: Two Souls", "Detroit: Become Human", "The Walking Dead: The Final Season", "Life is Strange", "Life is Strange: Before the Storm", "Life is Strange 2", "Tell Me Why", "Firewatch", "What Remains of Edith Finch", "Oxenfree", "Outer Wilds", "Spiritfarer", "Night in the Woods", "Kentucky Route Zero: TV Edition", "A Plague Tale: Innocence", "Brothers: A Tale of Two Sons", "Little Nightmares", "Little Nightmares II", "Inside", "Limbo", "Twelve Minutes", "Erica", "Until Dawn", "Man of Medan", "Little Hope", "House of Ashes", "The Quarry", "Gris", "Rime", "The Witness", "The Pathless", "Concrete Genie", "Abzû", "Subnautica", "Subnautica: Below Zero", "Telling Lies", "Lake", "Gone Home", "Dear Esther", "The Vanishing of Ethan Carter", "Deliver Us the Moon", "Thimbleweed Park", "Broken Age", "Return of the Obra Dinn", "Lost in Random"
        ],
        RPG: [
            "The Witcher 3: Wild Hunt", "Cyberpunk 2077", "Final Fantasy VII Remake", "Final Fantasy XV", "Final Fantasy XIV", "Dragon Quest XI S", "Persona 5", "Persona 5 Royal", "Tales of Arise", "Tales of Berseria", "Tales of Zestiria", "Elden Ring", "Bloodborne", "Demon's Souls", "Dark Souls III", "Dark Souls II: Scholar of the First Sin", "Dragon Age: Inquisition", "Mass Effect: Legendary Edition", "Fallout 4", "Fallout 76", "The Outer Worlds", "GreedFall", "Divinity: Original Sin II", "Pillars of Eternity", "Pillars of Eternity II: Deadfire", "Disco Elysium", "Ys VIII: Lacrimosa of Dana", "Ys IX: Monstrum Nox", "Ni no Kuni II: Revenant Kingdom", "Ni no Kuni: Wrath of the White Witch", "Kingdom Come: Deliverance", "Shin Megami Tensei III: Nocturne HD", "Atelier Ryza: Ever Darkness & the Secret Hideout", "Atelier Ryza 2: Lost Legends & the Secret Fairy", "Atelier Sophie: The Alchemist of the Mysterious Book", "Atelier Lulua: The Scion of Arland", "Xenoblade Chronicles Definitive Edition", "Xenoblade Chronicles 2", "SaGa Scarlet Grace: Ambitions", "Valkyria Chronicles 4", "Tokyo Xanadu eX+", "Blue Reflection", "The Legend of Heroes: Trails of Cold Steel III", "The Legend of Heroes: Trails of Cold Steel IV", "Monster Hunter World", "Monster Hunter Rise"
        ],
        Horror: [
            "Resident Evil 7: Biohazard", "Resident Evil Village", "Resident Evil 2 Remake", "Resident Evil 3 Remake", "The Evil Within", "The Evil Within 2", "Outlast", "Outlast 2", "Amnesia: Rebirth", "Amnesia: The Dark Descent", "SOMA", "Layers of Fear", "Layers of Fear 2", "Blair Witch", "Until Dawn", "Man of Medan", "Little Hope", "House of Ashes", "The Quarry", "Visage", "Phasmophobia", "Alien: Isolation", "Dead by Daylight", "Friday the 13th: The Game", "Slender: The Arrival", "Dark Pictures Anthology: The Devil in Me", "Martha Is Dead", "Tormented Souls", "MADiSON", "Call of Cthulhu", "Observer", "Observer: System Redux", "Daymare: 1998", "Dying Light", "Dying Light 2", "Carrion", "Hellblade: Senua's Sacrifice", "The Medium", "Silent Hill HD Collection", "Resident Evil 4 HD", "Condemned: Criminal Origins", "F.E.A.R.", "F.E.A.R. 2", "Dead Space", "Dead Space 2", "Dead Space 3", "DreadOut", "Fatal Frame: Maiden of Black Water", "Fatal Frame HD"
        ],
        Sports: [
            "FIFA 19", "FIFA 20", "FIFA 21", "FIFA 22", "Pro Evolution Soccer 2019", "Pro Evolution Soccer 2020", "Pro Evolution Soccer 2021", "NBA 2K19", "NBA 2K20", "NBA 2K21", "NBA 2K22", "Madden NFL 19", "Madden NFL 20", "Madden NFL 21", "Madden NFL 22", "NHL 19", "NHL 20", "NHL 21", "NHL 22", "MLB The Show 19", "MLB The Show 20", "MLB The Show 21", "MLB The Show 22", "Gran Turismo Sport", "Gran Turismo 7", "WRC 8", "WRC 9", "WRC 10", "Dirt Rally 2.0", "F1 2019", "F1 2020", "F1 2021", "F1 2022", "Tony Hawk's Pro Skater 1+2", "Skater XL", "Session", "Riders Republic", "Steep", "Olympic Games Tokyo 2020", "Tennis World Tour 2", "AO Tennis 2", "Football Manager 2020", "Football Manager 2021", "Football Manager 2022", "PGA Tour 2K21", "PGA Tour 2K22", "Rocket League", "Hot Wheels Unleashed"
        ]
    },        
    Xbox: {
        Action: ["Halo", "Gears of War", "Sunset Overdrive", "Crackdown 3", "Ryse: Son of Rome"],
        Adventure: ["Sea of Thieves", "Ori and the Blind Forest", "Ori and the Will of the Wisps", "Fable Anniversary", "Quantum Break"],
        RPG: ["Elden Ring", "The Outer Worlds", "Mass Effect Legendary Edition", "Dragon Age: Inquisition", "Wasteland 3"],
        Horror: ["Dead Space", "Alan Wake", "Resident Evil 4", "The Medium", "Layers of Fear"],
        Sports: ["Forza Horizon 5", "Madden NFL", "FIFA 22", "NBA Live 19", "Steep"]
    },
    "Nintendo Switch": {
        Action: ["Super Smash Bros.", "Bayonetta 3", "Splatoon 3", "Hyrule Warriors: Age of Calamity", "ARMS"],
        Adventure: ["Zelda: Breath of the Wild", "Luigi's Mansion 3", "Super Mario Odyssey", "Paper Mario: The Origami King", "Pikmin 3 Deluxe"],
        RPG: ["Pokémon Scarlet", "Fire Emblem", "Xenoblade Chronicles 3", "Octopath Traveler", "Dragon Quest Builders 2"],
        Horror: ["Little Nightmares", "Darkwood", "Resident Evil Revelations", "Dead by Daylight", "Outlast"],
        Sports: ["Mario Kart 8", "Ring Fit Adventure", "Nintendo Switch Sports", "Mario Golf: Super Rush", "Mario Tennis Aces"]
    },
    PC: {
        Action: [
            "DOOM Eternal", "DOOM (2016)", "Wolfenstein: The New Order", "Wolfenstein II: The New Colossus", "Far Cry 6", "Far Cry 5", "Far Cry 4", "Grand Theft Auto V", "Red Dead Redemption 2", "Assassin's Creed Valhalla", "Assassin's Creed Odyssey", "Assassin's Creed Origins", "Control", "Cyberpunk 2077", "Dishonored", "Dishonored 2", "Deathloop", "Shadow of the Tomb Raider", "Rise of the Tomb Raider", "Tomb Raider (2013)", "Middle-earth: Shadow of Mordor", "Middle-earth: Shadow of War", "Just Cause 4", "Just Cause 3", "Mad Max", "Batman: Arkham Asylum", "Batman: Arkham City", "Batman: Arkham Knight", "Hitman", "Hitman 2", "Hitman 3", "Metal Gear Solid V: The Phantom Pain", "Metal Gear Solid V: Ground Zeroes", "Nioh", "Nioh 2", "Sekiro: Shadows Die Twice", "Bloodborne (via emulation)", "Elden Ring", "Dark Souls III", "Dark Souls II", "Dark Souls: Remastered", "Devil May Cry 5", "Bayonetta", "Vanquish", "Darksiders", "Darksiders II", "Darksiders III", "Hades", "Dead Cells", "Celeste", "Hollow Knight", "Cuphead", "The Messenger", "Katana ZERO", "Hotline Miami", "Hotline Miami 2", "Shovel Knight", "Enter the Gungeon", "Risk of Rain 2", "Borderlands 3", "Borderlands 2", "Borderlands", "Watch Dogs", "Watch Dogs 2", "Watch Dogs Legion", "Sniper Elite 4", "Sniper Elite 3", "Sniper Ghost Warrior Contracts", "Call of Duty: Modern Warfare", "Call of Duty: Modern Warfare 2", "Call of Duty: Black Ops", "Call of Duty: Black Ops II"],
        Adventure: [
        "The Witcher 3: Wild Hunt", "Cyberpunk 2077", "Life is Strange", "Life is Strange: Before the Storm", "Life is Strange 2", "The Walking Dead: Season One", "The Walking Dead: Season Two", "The Walking Dead: A New Frontier", "The Wolf Among Us", "Tales from the Borderlands", "Firewatch", "What Remains of Edith Finch", "Oxenfree", "Night in the Woods", "Kentucky Route Zero", "A Plague Tale: Innocence", "A Plague Tale: Requiem", "Brothers: A Tale of Two Sons", "Gris", "Rime", "The Witness", "The Stanley Parable", "Gone Home", "Dear Esther", "The Vanishing of Ethan Carter", "Journey", "Abzû", "Spiritfarer", "Outer Wilds", "Return of the Obra Dinn", "Thimbleweed Park", "Broken Age", "Myst", "Syberia", "Syberia II", "Syberia 3", "Monkey Island: Special Edition", "Monkey Island 2: LeChuck's Revenge", "Tales of Monkey Island", "King's Quest", "The Long Dark", "Subnautica", "Subnautica: Below Zero", "The Pathless", "Little Nightmares", "Little Nightmares II", "Inside", "Limbo", "Twelve Minutes", "Erica", "Until Dawn", "Man of Medan", "Little Hope", "House of Ashes", "The Quarry", "Detroit: Become Human", "Beyond: Two Souls", "Heavy Rain", "Lake", "Telling Lies", "Shadow of the Colossus", "Ico", "Eastshade", "The Legend of Heroes: Trails in the Sky", "Bastion", "Transistor", "Pyre", "Forgotten Anne", "Carto", "Lost in Random", "Enslaved: Odyssey to the West", "Okami HD", "Concrete Genie", "Deliver Us the Moon", "Journey to the Savage Planet", "Call of the Sea", "Heaven's Vault", "The Gardens Between", "Creaks", "Afterparty", "Mutazione", "The Dark Pictures Anthology: The Devil in Me", "Road 96", "As Dusk Falls", "Norco", "Pentiment", "South of the Circle", "Unpacking", "Spiritfarer", "Lake", "Roadwarden", "Broken Pieces", "Lost Ember", "Memoir Blue", "Somerville", "Dordogne", "Harmony: The Fall of Reverie"]
    },
    Retro: {
        Action: ["Super Mario Bros.", "Sonic the Hedgehog", "Contra", "Mega Man 2", "Street Fighter II"],
        Adventure: ["Zelda: A Link to the Past", "Metroid", "Castlevania II: Simon's Quest", "Monkey Island", "Maniac Mansion"],
        RPG: ["Chrono Trigger", "Earthbound", "Final Fantasy VI", "Secret of Mana", "Dragon Quest III"],
        Horror: ["Castlevania", "Clock Tower", "Sweet Home", "Alone in the Dark", "Splatterhouse"],
        Sports: ["Tecmo Bowl", "NBA Jam", "Punch-Out!!", "California Games", "Blades of Steel"]
    },
    NES: {
        Action: ["Super Mario Bros.", "The Legend of Zelda", "Metroid", "Castlevania", "Mega Man"],
        Adventure: ["Kirby's Adventure", "Maniac Mansion", "Zelda II: The Adventure of Link", "Dragon Warrior", "StarTropics"],
        RPG: ["Final Fantasy", "Dragon Warrior III", "Crystalis", "The Magic of Scheherazade", "Faxanadu"],
        Horror: ["Sweet Home", "Friday the 13th", "Nightmare on Elm Street", "Shadowgate", "Ghoul School"],
        Sports: ["Punch-Out!!", "Tecmo Bowl", "Ice Hockey", "Excitebike", "Baseball Stars"]
    },
    SNES: {
        Action: ["Super Mario World", "Donkey Kong Country", "Mega Man X", "Contra III: The Alien Wars", "F-Zero", "Super Ghouls 'n Ghosts", "Pilotwings", "Axelay", "Wild Guns", "The Ninja Warriors", "Turtles in Time", "ActRaiser 2", "Super Adventure Island", "Doom Troopers", "Cybernator", "Battletoads & Double Dragon", "Pocky & Rocky", "Sunset Riders", "Batman Returns", "Earthworm Jim"],
        Adventure: ["The Legend of Zelda: A Link to the Past", "Super Metroid", "ActRaiser", "Secret of Evermore", "Out of This World", "Illusion of Gaia", "The Adventures of Batman & Robin", "Shadowrun", "Star Fox", "Prince of Persia", "Another World", "Plok", "Super Mario RPG: Legend of the Seven Stars", "Mystic Quest", "Soul Blazer", "Equinox", "Flashback", "Prehistorik Man", "Terranigma", "Alcahest"],
        RPG: ["Chrono Trigger", "Final Fantasy VI", "EarthBound", "Secret of Mana", "Breath of Fire II", "Final Fantasy IV", "Lufia II: Rise of the Sinistrals", "Super Mario RPG: Legend of the Seven Stars", "Dragon Quest V", "Illusion of Gaia", "The 7th Saga", "Ogre Battle: The March of the Black Queen", "Secret of Evermore", "Tales of Phantasia", "Rudra no Hihou", "Bahamut Lagoon", "Treasure of the Rudras", "Der Langrisser", "Front Mission", "Terranigma"],
        Horror: ["Super Castlevania IV", "Clock Tower", "Demon's Crest", "Zombies Ate My Neighbors", "Nosferatu", "Super Ghouls 'n Ghosts", "Chakan: The Forever Man", "Haunting Ground", "Splatterhouse 2", "Splatterhouse 3", "Ghoul Patrol", "Alone in the Dark", "The Twisted Tales of Spike McFang", "Zombie Nation", "Lagoon", "Mighty Max", "Jaki Crush", "Illbleed", "Shadowgate", "Out of This World"],
        Sports: ["NBA Jam", "Super Punch-Out!!", "Ken Griffey Jr.'s Winning Run", "Super Baseball Simulator 1.000", "Super Soccer", "FIFA International Soccer", "Super Tennis", "NHL '94", "International Superstar Soccer Deluxe", "Super Mario Kart", "World Cup USA '94", "Cal Ripken Jr. Baseball", "Tony Meola's Sidekicks Soccer", "NCAA Basketball", "Hyper V-Ball", "Extra Innings", "Super Bowling", "Winter Gold", "Jimmy Connors Pro Tennis Tour", "Tecmo Super Bowl"]
    }
    
};

document.getElementById("generate").addEventListener("click", () => {
    const console = document.getElementById("console").value;
    const genre = document.getElementById("genre").value;

    if (games[console] && games[console][genre]) {
        const randomGame = games[console][genre][Math.floor(Math.random() * games[console][genre].length)];
        document.getElementById("result").innerHTML = `<h3>Suggested Game:</h3><p>${randomGame}</p>`;
    } else {
        document.getElementById("result").innerHTML = `<p>No games available for this selection.</p>`;
    }
});
